### ISSUE TITLE
Option to match only on full URL

### ISSUE THREAD

**Issue by rugk** [smorks/keepasshttp-connector#64] opened 2017-12-20 21:00 UTC
Under one domain, there may be several services or other things that require different passwords.

It would be nice if one could enable an option (preferably per password entry in KeePassX) to only match on the full URL (or `/subdirs?andother&thin#gs`; i.e. just act as a prefix) and not on the domain.

**Comment by smorks** [comment] 2017-12-20 21:09
i believe there's a global option that does this.

In KeePassXC: Settings -> Browser Integration -> General ->Return only best matching entries
And in KeePass it's in the KeePassHttp Options.

i haven't tested with the option on, but that sounds like what you want. i'll label this as an enhancement to look at doing something per entry.

**Comment by rugk** [comment] 2017-12-20 21:20
Ahh… thanks.

In the German translation it is labeled "Only show best results.". Maybe that's also not so obvious… Should I open an issue for KeePassXC or can I directly change the translation somewhere?
But even the English one is not really obvious… "best matching" is relative. "Full URL vs domain-match-only" is a better thing.

Same for "use URL schema". Also not obvious…

**Comment by rugk** [comment] 2017-12-20 21:27
Hmm… but somehow it does not seem to work. Still offers me all passwords…

**Comment by smorks** [comment] 2017-12-21 05:22
this works for me in KeePass, and on further investigation, it looks like it's a bug in KeePassXC:

keepassxreboot/keepassxc#1112

i'm going to close this issue since there's nothing that can be done in the browser extension to fix this.

**Closed by smorks** 2017-12-21 05:22 UTC
Labels: enhancement

**Comment by MarkusPiotrowski** [comment] 2018-02-15 10:13
It would be nice to re-open this. I have a similar problem where I have to log-in on the main page of a service and then, on a sub-page, I can enter login information for *other users*. However, if I use the auto-fill option of KeePassHttp-Connector, it will always overwrite these information with *my* login data (if you are interested: it's about Moodle). 
I'm using KeePass2 and in the KeePassHttp settings I have already ticked "Return only best matching url..." and also "Match URL schemes". It doesn't work. The problem is, I don't wan't alternative log-in but I don't want any log-in for the sub-page. So it would be nice if there would be an option in KeePassHttp-Connector for not using autofill for a certain page. E.g. similar to the "Choose own credential fields.." button.
