### ISSUE TITLE
jquery ui styles are overridden for each page

### ISSUE THREAD

**Issue by rengaw83** [smorks/keepasshttp-connector#36] opened 2017-11-16 08:11 UTC
Hi, 
sinse version 1.0.5 the jquery ui is loaded on each site i open in firefox.
the base jquery ui css overrides the css of the pages content.

you can see this directy in the jqueryui examples: https://jqueryui.com/dialog/

here are a dialog with custom styles, all these styles are overridden by this extension: https://www.tutorialspoint.com/jqueryui/src/dialog_functionality.htm

**Comment by varjolintu** [comment] 2017-11-16 08:15
That's the reason original PassIFox made a custom version of the jQuery UI. Same happens if you put a Bootstrap CSS to content_scripts.

In what pages can you see the overriding? I'm asking this because I might have the same problem with my fork.

**Comment by rengaw83** [comment] 2017-11-16 09:11
I have a lot of internal tools like ticketsystems. most of this tools are using bootstrap and jquery ui and i cant use the tools or keepasshttp anymore.

i cant get you access to this tools, but the dialog example from [tutorialspoint](https://www.tutorialspoint.com/jqueryui/src/dialog_functionality.htm) shows the problem very well

**Comment by z3ntu** [comment] 2017-11-16 09:21
Can reproduce the issue.

**Comment by varjolintu** [comment] 2017-11-16 09:35
I think the solution for this is to download a custom jQuery UI with a certain CSS scope and use that so the styles won't collide.

**Comment by smorks** [comment] 2017-11-16 14:48
sorry everyone, i was in a rush to get a release back onto AMO when they took it down, and didn't do a whole lot of testing.

@varjolintu i will try that out, thanks!

**Comment by jagmoreira** [comment] 2017-11-17 00:49
I think I'm having the same issue with Jupyter notebooks. See https://github.com/jupyter/notebook/issues/3047

Basically, since the extension was updated, the tooltip icons in the notebooks disappear.

**Comment by smorks** [comment] 2017-11-17 04:53
this should be fixed with commit 8cca5d5d7b888d8cad2b24ac8b89990e5db0864c, and will be in version 1.0.6.

**Closed by smorks** 2017-11-17 04:53 UTC

**Comment by rengaw83** [comment] 2017-11-17 07:13
Works as expected now. Thank you!
